# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/suez/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/suez/proprietary/etc/.tp/thermal.conf:system/etc/.tp/thermal.conf \
    vendor/amazon/suez/proprietary/etc/.tp/thermal.off.conf:system/etc/.tp/thermal.off.conf \
    vendor/amazon/suez/proprietary/etc/.tp/thermal.policy.conf:system/etc/.tp/thermal.policy.conf \
    vendor/amazon/suez/proprietary/lib/libcjson.so:system/lib/libcjson.so \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/anlg_dock_headset.csv:system/vendor/smartvolume/suez/anlg_dock_headset.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/aux_digital.csv:system/vendor/smartvolume/suez/aux_digital.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/bt_a2dp.csv:system/vendor/smartvolume/suez/bt_a2dp.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/bt_a2dp_headphones.csv:system/vendor/smartvolume/suez/bt_a2dp_headphones.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/bt_a2dp_speaker.csv:system/vendor/smartvolume/suez/bt_a2dp_speaker.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/bt_sco.csv:system/vendor/smartvolume/suez/bt_sco.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/bt_sco_carkit.csv:system/vendor/smartvolume/suez/bt_sco_carkit.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/bt_sco_headset.csv:system/vendor/smartvolume/suez/bt_sco_headset.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/default.csv:system/vendor/smartvolume/suez/default.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/dgtl_dock_headeset.csv:system/vendor/smartvolume/suez/dgtl_dock_headeset.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/speaker.csv:system/vendor/smartvolume/suez/speaker.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/wired_headphone.csv:system/vendor/smartvolume/suez/wired_headphone.csv \
    vendor/amazon/suez/proprietary/vendor/smartvolume/suez/wired_headset.csv:system/vendor/smartvolume/suez/wired_headset.csv
